function(Add_CXX_Sub_Library name src_files inc_path libs)
    if(output_path_libs)
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${output_path_lib})
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${output_path_lib})
    else()
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${PROJECT_NAME}/lib)
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${PROJECT_NAME}/lib)
    endif()
    file(GLOB_RECURSE src "${src_files}")

    add_library(${name}_shared SHARED ${src})
    target_include_directories(${name}_shared PUBLIC ${inc_path})
    target_link_libraries(${name}_shared ${libs})
    set_target_properties(${name}_shared PROPERTIES OUTPUT_NAME ${name})

    add_library(${name}_static STATIC ${src})
    target_include_directories(${name}_static PUBLIC ${inc_path})
    target_link_libraries(${name}_static ${libs})
    set_target_properties(${name}_static PROPERTIES OUTPUT_NAME ${name})
    unset(src)
endfunction()

function(Add_CXX_Unit_Test name test_src inc_path deps libs)
    set(test_obj test_${name})
    if(output_path_test)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${output_path_test})
    else()
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${PROJECT_NAME}/test)
    endif()
    if(output_path_libs)
        link_directories(${CMAKE_BINARY_DIR}/${output_path_lib})
    else()
        link_directories(${CMAKE_BINARY_DIR}/${PROJECT_NAME}/lib)
    endif()
    add_executable(${test_obj} ${test_src})
    add_dependencies(${test_obj} ${deps})
    target_include_directories(${test_obj} PUBLIC ${inc_path})
    target_link_libraries(${test_obj} ${libs})
    unset(test_obj)
endfunction()

function(Compile_CXX_Test test_files inc_path deps libs)
    file(GLOB_RECURSE test_src "${test_files}")
    foreach(src ${test_src})
        get_filename_component(name ${src} NAME_WE)
        Add_CXX_Unit_Test("${name}" "${src}" "${inc_path}" "${deps}" "${libs}")
    endforeach(src)
endfunction()

